[workspace]
members = [
  "crates/unknown/lang/reader/lexer",
  "crates/unknown/lang/reader/syntax",
  "crates/unknown/lang/reader/token",
]


[profile.release]
codegen-units = 1
incremental = false
lto = true
opt-level = "s"
panic = "abort"
