name: audit


on:
  schedule:
    # every week
    - cron: '0 0 * * 0'
  push:
    paths:
      - "Cargo.lock"
      - "Cargo.toml"


jobs:
  audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
